name: Output Event "issues"
on: 
    issues:
        types: [opened, edited]
jobs: 
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output event details
              run: echo "${{ toJson(github.event) }}"